{% set name = "lineedit" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lineedit-{{ version }}.tar.gz
  sha256: f4795479154e350ad9cf6e8be6ad3a78f10f892b99675af2f8140f2d847f6f3f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pygments
    - python >={{ python_min }}
    - six >=1.9.0
    - wcwidth

test:
  imports:
    - lineedit
    - lineedit.deps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randy3k/lineedit
  summary: An readline library based on prompt_toolkit which supports multiple modes
  license: MIT
  license_file:
    - LICENSE.md
    # This package vendors an older version of prompt_toolkit for Python 2 compatibility
    - lineedit/deps/LICENSE

extra:
  recipe-maintainers:
    - randy3k
    - jdblischak
